export enum WebSocketEvent {
	SET_ADDRESS = 'SET_ADDRESS',
	SET_SESSION_ID = 'SET_SESSION_ID',
	PROOF_GENERATING = 'PROOF_GENERATING',
	PROOF_SAVING = 'PROOF_SAVING',
	PROOF_SAVED = 'PROOF_SAVED',
	PROOF_ERROR = 'PROOF_ERROR',
}
